version: '3'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    volumes:
      - database-data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    expose:
      - 5432
    networks:
      - local

  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/home/node/app
      - /home/node/app/node_modules
    ports:
      - 80:80
    depends_on:
      - db
    networks:
      - local

volumes:
  database-data:

networks:
  local:
